name: 'Code Quality'
on:
  pull_request:
    branches:
      - develop
      - main
      - feat/*
      - hotfix/*

jobs:
  publish:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: yarn
      - run: yarn lint
      - run: yarn jest
